name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install and Test
        run: |
          pip install --upgrade pip
          # Install your package in editable mode
          pip install -e .
          # Also ensure pytest is installed (or put it in setup.py)
          pip install pytest
          # Now run tests
          pytest --maxfail=1 --disable-warnings
